<?php
/**
 * Generates the Supabase-side migration SQL.
 *
 * The SQL is generated rather than hand-written so the table always matches
 * PostMapper's field list and the configured table name. Drift between the
 * mapper and the table is one of the failure modes the diagnostics exist to
 * catch; not being able to introduce it in the first place is better.
 *
 * The GRANT block is exposed separately because Diagnostics quotes it as the
 * copy-pasteable fix for a `42501`, and a fix the user has to assemble by hand
 * is not much of a fix.
 *
 * @package WPSupabaseSync
 */

declare( strict_types=1 );

namespace WPSupabaseSync\Sync;

use WPSupabaseSync\Settings\Settings;

defined( 'ABSPATH' ) || exit;

final class Schema {

	/**
	 * Status value the diagnostics write probe uses.
	 *
	 * Anything other than 'publish' would do, but a distinctive value makes a
	 * stray probe row obvious in the table if one ever survives a crash.
	 */
	public const PROBE_STATUS = '_probe';

	public const PROBE_POST_TYPE = '_wpsb_probe';

	public function __construct( private readonly Settings $settings ) {}

	/**
	 * The complete migration.
	 */
	public function migration(): string {
		$table = $this->settings->table_name();

		return implode(
			"\n",
			array(
				'-- WP Supabase Sync — content mirror table.',
				'-- Generated by `wp supabase schema --print`. Do not hand-edit: regenerate.',
				'',
				$this->table_sql( $table ),
				'',
				$this->indexes_sql( $table ),
				'',
				self::rls_sql( $table ),
				'',
				self::grants_sql( $table ),
				'',
				self::policy_sql( $table ),
				'',
			)
		);
	}

	private function table_sql( string $table ): string {
		$lines = array( "create table if not exists public.{$table} (" );

		// `generated always as identity` rather than serial: identity columns do
		// not create a separate sequence object that would need its own grant.
		$lines[] = '  id                 bigint generated always as identity primary key,';

		$definitions = PostMapper::column_definitions();
		$width       = max( array_map( 'strlen', array_keys( $definitions ) ) );

		foreach ( $definitions as $column => $type ) {
			$lines[] = sprintf( '  %-' . $width . 's %s,', $column, $type );
		}

		$lines[] = '  synced_at          timestamptz not null default now(),';
		$lines[] = '  unique ( site_id, wp_id )';
		$lines[] = ');';

		return implode( "\n", $lines );
	}

	private function indexes_sql( string $table ): string {
		return implode(
			"\n",
			array(
				"create index if not exists {$table}_lookup_idx",
				"  on public.{$table} ( site_id, post_type, status );",
				"create index if not exists {$table}_slug_idx",
				"  on public.{$table} ( site_id, slug );",
				"create index if not exists {$table}_terms_idx",
				"  on public.{$table} using gin ( terms );",
			)
		);
	}

	public static function rls_sql( string $table ): string {
		return "alter table public.{$table} enable row level security;";
	}

	/**
	 * Table privileges — layer one of the two-layer permission model.
	 *
	 * This block is the whole lesson from the companion playbook. Migrations run
	 * as `postgres`, and this image's default privileges for `postgres` in schema
	 * `public` do **not** include DML for anon, authenticated or service_role.
	 * Without these grants every policy below is unreachable and the API returns
	 * `42501 permission denied for table` — row level security is never even
	 * consulted.
	 *
	 * service_role needs a grant too. It bypasses RLS but **not** table
	 * privileges, so without this the service key gets 42501 as well.
	 */
	public static function grants_sql( string $table ): string {
		return implode(
			"\n",
			array(
				'-- Layer 1: table privileges. RLS is never consulted without these.',
				"revoke all on public.{$table} from anon, authenticated;",
				"grant select on public.{$table} to anon, authenticated;",
				"grant select, insert, update, delete on public.{$table} to service_role;",
			)
		);
	}

	/**
	 * Row policies — layer two.
	 *
	 * Only published rows are publicly readable. service_role bypasses RLS and
	 * so needs no policy, but it did need the grant above.
	 */
	public static function policy_sql( string $table ): string {
		return implode(
			"\n",
			array(
				'-- Layer 2: row policies. service_role bypasses RLS, so it needs no policy —',
				'-- but it DID need the grant above.',
				"drop policy if exists \"Published content is publicly readable\" on public.{$table};",
				'create policy "Published content is publicly readable"',
				"  on public.{$table} for select",
				'  to anon, authenticated',
				"  using ( status = 'publish' );",
			)
		);
	}
}
