-- WP Supabase Sync — content mirror table.
-- Generated by `wp supabase schema --print`. Do not hand-edit: regenerate.

create table if not exists public.wp_content (
  id                 bigint generated always as identity primary key,
  site_id            text        not null,
  wp_id              bigint      not null,
  post_type          text        not null,
  status             text        not null,
  slug               text        not null,
  title              text,
  excerpt            text,
  content_html       text,
  author_name        text,
  featured_image_url text,
  url                text,
  published_at       timestamptz,
  modified_at        timestamptz,
  meta               jsonb       not null default '{}'::jsonb,
  terms              jsonb       not null default '[]'::jsonb,
  content_hash       text        not null,
  synced_at          timestamptz not null default now(),
  unique ( site_id, wp_id )
);

create index if not exists wp_content_lookup_idx
  on public.wp_content ( site_id, post_type, status );
create index if not exists wp_content_slug_idx
  on public.wp_content ( site_id, slug );
create index if not exists wp_content_terms_idx
  on public.wp_content using gin ( terms );

alter table public.wp_content enable row level security;

-- Layer 1: table privileges. RLS is never consulted without these.
revoke all on public.wp_content from anon, authenticated;
grant select on public.wp_content to anon, authenticated;
grant select, insert, update, delete on public.wp_content to service_role;

-- Layer 2: row policies. service_role bypasses RLS, so it needs no policy —
-- but it DID need the grant above.
drop policy if exists "Published content is publicly readable" on public.wp_content;
create policy "Published content is publicly readable"
  on public.wp_content for select
  to anon, authenticated
  using ( status = 'publish' );

